/**
 * Staff domain E2E tests — migrated from e2e/api-gateway-e2e/hurl/staff/*.hurl
 *
 * Covers:
 *   01-create-staff — createStaffMember generates employeeId via
 *                     tenant_sequences; core fields persisted (designation,
 *                     department, dateOfJoining, employmentType)
 *   02-list-staff   — listStaff returns the tenant's members; filterable by
 *                     department
 *
 * Note: cross-scope rejection + cross-tenant isolation are already covered
 * by the integration test suite (staff-list.integration.spec.ts). This file
 * focuses on the external-HTTP surface that exercises the full running
 * stack (validator, resolver, withTenant, RLS, sequence allocator).
 */
import assert from 'node:assert';
import { EmploymentType, Gender } from '@roviq/common-types';
import { beforeAll, describe, expect, it } from 'vitest';

import { loginAsInstituteAdmin } from './helpers/auth';
import { gql } from './helpers/gql-client';

interface StaffNode {
  id: string;
  employeeId: string;
  designation: string | null;
  department: string | null;
  employmentType: EmploymentType | null;
  dateOfJoining: string | null;
}

describe('Staff E2E', () => {
  let accessToken: string;
  let createdStaffId: string;

  beforeAll(async () => {
    const admin = await loginAsInstituteAdmin();
    accessToken = admin.accessToken;
  });

  // ─────────────────────────────────────────────────────
  // 01-create-staff
  // ─────────────────────────────────────────────────────
  describe('createStaffMember', () => {
    it('generates an employeeId via tenant_sequences and persists core fields', async () => {
      const res = await gql<{ createStaffMember: StaffNode }>(
        `mutation CreateStaff($input: CreateStaffInput!) {
          createStaffMember(input: $input) {
            id employeeId designation department dateOfJoining employmentType
          }
        }`,
        {
          input: {
            firstName: { en: 'Rajesh' },
            lastName: { en: 'Sharma' },
            gender: Gender.MALE,
            designation: 'PGT Physics',
            department: 'Science',
            dateOfJoining: '2025-04-01',
            employmentType: EmploymentType.REGULAR,
            phone: '9876501001',
          },
        },
        accessToken,
      );

      expect(res.errors).toBeUndefined();
      const staff = res.data?.createStaffMember;
      assert(staff);
      expect(staff.id).toBeTruthy();
      // employeeId is generated by the tenant_sequences function — should be
      // a non-empty, formatted string (e.g. "EMP-2025-0001").
      expect(staff.employeeId).toBeTruthy();
      expect(staff.designation).toBe('PGT Physics');
      expect(staff.department).toBe('Science');
      expect(staff.employmentType).toBe(EmploymentType.REGULAR);

      createdStaffId = staff.id;
    });
  });

  // ─────────────────────────────────────────────────────
  // 02-list-staff
  // ─────────────────────────────────────────────────────
  describe('listStaff', () => {
    it('returns the tenant staff list', async () => {
      const res = await gql<{ listStaff: StaffNode[] }>(
        `query { listStaff { id employeeId designation department } }`,
        {},
        accessToken,
      );
      expect(res.errors).toBeUndefined();
      assert(res.data);
      expect(Array.isArray(res.data.listStaff)).toBe(true);
      // The staff member we just created must be in the list.
      const ids = res.data.listStaff.map((s) => s.id);
      expect(ids).toContain(createdStaffId);
    });

    it('filters by department', async () => {
      const res = await gql<{ listStaff: StaffNode[] }>(
        `query ListFiltered($filter: ListStaffFilterInput) {
          listStaff(filter: $filter) { id department }
        }`,
        { filter: { department: 'Science' } },
        accessToken,
      );
      expect(res.errors).toBeUndefined();
      assert(res.data);
      expect(Array.isArray(res.data.listStaff)).toBe(true);
      // If anything is returned, every row must match the filter.
      for (const row of res.data.listStaff) {
        expect(row.department).toBe('Science');
      }
    });
  });
});
