#!/bin/bash
set -euo pipefail

echo "=== Roviq Dev Container: postCreate ==="

# Enable corepack and install pnpm (version from packageManager field)
corepack enable
corepack install

# Install dependencies (CI=true avoids TTY prompts in non-interactive shells)
echo "Installing dependencies..."
CI=true pnpm install

# Create .env from .env.example if it doesn't exist, with Docker service hostnames.
# Patched services (available in devcontainer): PostgreSQL, Redis, NATS.
# NOT patched (not in devcontainer compose): Temporal, MinIO, MongoDB, OTEL.
# To add those, extend .devcontainer/docker-compose.yml and patch here.
if [ ! -f .env ]; then
  echo "Creating .env from .env.example with Docker hostnames..."
  cp .env.example .env

  # Patch DATABASE_URL* vars specifically (not a blind global replace)
  sed -i 's|DATABASE_URL=\(.*\)localhost:5432|DATABASE_URL=\1postgres:5432|g' .env
  sed -i 's|DATABASE_URL_MIGRATE=\(.*\)localhost:5432|DATABASE_URL_MIGRATE=\1postgres:5432|g' .env
  sed -i 's|DATABASE_URL_AUDIT=\(.*\)localhost:5432|DATABASE_URL_AUDIT=\1postgres:5432|g' .env
  sed -i 's|DATABASE_URL_TEST=\(.*\)localhost:5432|DATABASE_URL_TEST=\1postgres:5432|g' .env
  sed -i 's|DATABASE_URL_TEST_MIGRATE=\(.*\)localhost:5432|DATABASE_URL_TEST_MIGRATE=\1postgres:5432|g' .env

  # Patch Redis URL
  sed -i 's|REDIS_URL=redis://localhost:6379|REDIS_URL=redis://redis:6379|' .env

  # Patch NATS URL
  sed -i 's|NATS_URL=nats://localhost:4222|NATS_URL=nats://nats:4222|' .env

  echo "# Generated by devcontainer postCreate.sh — patched for Docker service hostnames" >> .env
fi

# Install Playwright Chromium browser + system dependencies for e2e tests
echo "Installing Playwright Chromium browser..."
sudo pnpm exec playwright install --with-deps chromium

echo "=== postCreate complete ==="
