import { randomUUID } from 'node:crypto';
import { hash } from '@node-rs/argon2';
import {
  type DrizzleDB,
  institutes,
  memberships,
  resellerMemberships,
  resellers,
  roles,
  SYSTEM_USER_ID,
  users,
  withAdmin,
} from '@roviq/database';
import { and, eq } from 'drizzle-orm';

/**
 * Default reseller ID seeded in every environment as "Roviq Direct".
 * Institutes created without an explicit reseller belong to this reseller.
 *
 * Source of truth: `scripts/seed-ids.ts → SEED_IDS.RESELLER_DIRECT`.
 */
export const RESELLER_DIRECT_ID = '00000000-0000-0000-0000-000000000001';

/** Full-access abilities used as a default for test memberships. */
const TEST_ABILITIES = [{ action: 'manage', subject: 'all' }] as const;

/**
 * Limited abilities mirroring the seeded `class_teacher` role
 * (`libs/shared/common-types/src/lib/common-types.ts → DEFAULT_ROLE_ABILITIES.class_teacher`).
 *
 * The `$user.assignedSections` placeholder is substituted to `[]` at request
 * time when the test teacher has no assigned sections, so any row-level CASL
 * filter will be empty — every section-conditioned read fails. That is fine
 * for tests asserting unconditional FORBIDDEN responses on
 * create/update/delete actions, which the teacher does not have at all.
 */
const TEST_TEACHER_ABILITIES = [
  {
    action: 'read',
    subject: 'Student',
    conditions: { sectionId: { $in: '$user.assignedSections' } },
  },
  {
    action: 'manage',
    subject: 'Attendance',
    conditions: { sectionId: { $in: '$user.assignedSections' } },
  },
  {
    action: 'read',
    subject: 'Guardian',
    conditions: { sectionId: { $in: '$user.assignedSections' } },
  },
  { action: 'read', subject: 'Section' },
  { action: 'read', subject: 'Standard' },
  { action: 'read', subject: 'Subject' },
  { action: 'read', subject: 'AcademicYear' },
  { action: 'read', subject: 'Institute' },
] as const;

export interface TestInstitute {
  /** Institute / tenant ID — use as `tenantId` in `createInstituteToken()`. */
  tenantId: string;
  /** Unique slug for debugging / assertion. */
  slug: string;
  /** Admin user ID — pass as `sub` to `createInstituteToken()`. */
  userId: string;
  /** Membership ID — pass as `membershipId` to `createInstituteToken()`. */
  membershipId: string;
  /** Institute-scoped role ID — pass as `roleId` to `createInstituteToken()`. */
  roleId: string;
  /** Username assigned to the admin user. */
  username: string;
}

export interface CreateTestInstituteOptions {
  /**
   * Override the parent reseller. Defaults to `RESELLER_DIRECT_ID`, which is
   * always present in seeded environments.
   */
  resellerId?: string;
  /**
   * Override the slug suffix. Defaults to a random 8-char crypto suffix.
   */
  slugSuffix?: string;
  /**
   * Plaintext password to hash with argon2 and store on the user row. If
   * omitted, the user is created with a dummy hash — sufficient for tests
   * that don't exercise the real `instituteLogin` flow.
   */
  password?: string;
}

const DUMMY_PASSWORD_HASH = 'not-a-real-hash-for-tests-without-login-flow';

/**
 * Create a fresh institute + admin user + institute-scoped role + membership
 * inside a single transaction, returning the IDs needed to mint an
 * `institute`-scoped token.
 *
 * Uses `withAdmin()` from `@roviq/database` so RLS is bypassed exactly as
 * production admin operations do. UUIDs are generated by Postgres via
 * `DEFAULT uuidv7()`, so they cannot collide with seed data.
 *
 * The created membership has `abilities: [{ action: 'manage', subject: 'all' }]`
 * so CASL grants the test admin every permission.
 *
 * Note: this factory intentionally does NOT create academic_years, branding,
 * configs, or identifiers. Tests that need those must create them explicitly
 * or extend this helper.
 */
export async function createTestInstitute(
  db: DrizzleDB,
  options: CreateTestInstituteOptions = {},
): Promise<TestInstitute> {
  const slugSuffix = options.slugSuffix ?? randomUUID().slice(0, 8);
  const slug = `test-${slugSuffix}`;
  const username = `test_admin_${slugSuffix}`;
  const resellerId = options.resellerId ?? RESELLER_DIRECT_ID;
  const passwordHash = options.password ? await hash(options.password) : DUMMY_PASSWORD_HASH;

  return withAdmin(db, async (tx) => {
    const [institute] = await tx
      .insert(institutes)
      .values({
        name: { en: `Test Institute ${slugSuffix}` },
        slug,
        resellerId,
        createdBy: SYSTEM_USER_ID,
        updatedBy: SYSTEM_USER_ID,
      })
      .returning({ id: institutes.id });

    const [user] = await tx
      .insert(users)
      .values({
        email: `${username}@test.local`,
        username,
        passwordHash,
      })
      .returning({ id: users.id });

    const [role] = await tx
      .insert(roles)
      .values({
        name: { en: 'Test Institute Admin' },
        scope: 'institute',
        tenantId: institute.id,
        abilities: TEST_ABILITIES,
        isDefault: false,
        isSystem: false,
        createdBy: SYSTEM_USER_ID,
        updatedBy: SYSTEM_USER_ID,
      })
      .returning({ id: roles.id });

    const [membership] = await tx
      .insert(memberships)
      .values({
        userId: user.id,
        roleId: role.id,
        tenantId: institute.id,
        abilities: TEST_ABILITIES,
        createdBy: user.id,
        updatedBy: user.id,
      })
      .returning({ id: memberships.id });

    return {
      tenantId: institute.id,
      slug,
      userId: user.id,
      membershipId: membership.id,
      roleId: role.id,
      username,
    };
  });
}

export interface TestTeacher {
  /** Teacher user ID — pass as `sub` to `createInstituteToken()`. */
  userId: string;
  /** Membership ID — pass as `membershipId` to `createInstituteToken()`. */
  membershipId: string;
  /** Tenant-scoped role ID — pass as `roleId` to `createInstituteToken()`. */
  roleId: string;
  /** Username assigned to the teacher user. */
  username: string;
}

/**
 * Create a fresh teacher user + tenant-scoped role + membership inside an
 * existing test institute. The role mirrors the seeded `class_teacher`
 * abilities (read Student/Section/Standard/Subject/AcademicYear/Institute,
 * manage Attendance — all section-conditioned where applicable).
 *
 * Use this to verify that `@CheckAbility` decorators block actions a
 * teacher does not have permission to perform (e.g. create/delete Student,
 * create Standard, update Institute info).
 *
 * The seeded `class_teacher` role belongs to `SEED.INSTITUTE_1` and cannot
 * be reused for a fresh test tenant — roles are tenant-scoped.
 */
export async function createTestTeacher(db: DrizzleDB, tenantId: string): Promise<TestTeacher> {
  const slugSuffix = randomUUID().slice(0, 8);
  const username = `test_teacher_${slugSuffix}`;

  return withAdmin(db, async (tx) => {
    const [user] = await tx
      .insert(users)
      .values({
        email: `${username}@test.local`,
        username,
        passwordHash: DUMMY_PASSWORD_HASH,
      })
      .returning({ id: users.id });

    const [role] = await tx
      .insert(roles)
      .values({
        name: { en: `Test Class Teacher ${slugSuffix}` },
        scope: 'institute',
        tenantId,
        abilities: TEST_TEACHER_ABILITIES,
        isDefault: false,
        isSystem: false,
        createdBy: SYSTEM_USER_ID,
        updatedBy: SYSTEM_USER_ID,
      })
      .returning({ id: roles.id });

    const [membership] = await tx
      .insert(memberships)
      .values({
        userId: user.id,
        roleId: role.id,
        tenantId,
        abilities: TEST_TEACHER_ABILITIES,
        createdBy: user.id,
        updatedBy: user.id,
      })
      .returning({ id: memberships.id });

    return {
      userId: user.id,
      membershipId: membership.id,
      roleId: role.id,
      username,
    };
  });
}

/**
 * Delete the user row created by `createTestTeacher`. The role + membership
 * live inside the tenant and are cleaned up by `cleanupTestInstitute`, but
 * the user row is tenant-independent and must be removed separately.
 */
export async function cleanupTestTeacher(db: DrizzleDB, teacher: TestTeacher): Promise<void> {
  await withAdmin(db, async (tx) => {
    await tx.delete(memberships).where(eq(memberships.id, teacher.membershipId));
    await tx.delete(roles).where(eq(roles.id, teacher.roleId));
    await tx.delete(users).where(eq(users.id, teacher.userId));
  });
}

export interface TestReseller {
  resellerId: string;
  userId: string;
  membershipId: string;
  roleId: string;
  username: string;
}

/**
 * Create a fresh reseller + admin user + reseller-scoped role + membership.
 */
export async function createTestReseller(db: DrizzleDB): Promise<TestReseller> {
  const slugSuffix = randomUUID().slice(0, 8);
  const slug = `test-reseller-${slugSuffix}`;
  const username = `test_reseller_${slugSuffix}`;

  return withAdmin(db, async (tx) => {
    const [reseller] = await tx
      .insert(resellers)
      .values({ name: `Test Reseller ${slugSuffix}`, slug })
      .returning({ id: resellers.id });

    const [user] = await tx
      .insert(users)
      .values({
        email: `${username}@test.local`,
        username,
        passwordHash: DUMMY_PASSWORD_HASH,
      })
      .returning({ id: users.id });

    const [role] = await tx
      .insert(roles)
      .values({
        name: { en: 'Test Reseller Admin' },
        scope: 'reseller',
        resellerId: reseller.id,
        abilities: TEST_ABILITIES,
        isDefault: false,
        isSystem: false,
        createdBy: SYSTEM_USER_ID,
        updatedBy: SYSTEM_USER_ID,
      })
      .returning({ id: roles.id });

    const [membership] = await tx
      .insert(resellerMemberships)
      .values({
        userId: user.id,
        roleId: role.id,
        resellerId: reseller.id,
        abilities: TEST_ABILITIES,
      })
      .returning({ id: resellerMemberships.id });

    return {
      resellerId: reseller.id,
      userId: user.id,
      membershipId: membership.id,
      roleId: role.id,
      username,
    };
  });
}

/**
 * Delete everything `createTestInstitute` created: membership → role →
 * institute → user. Call from `afterAll` to keep the test database tidy.
 */
export async function cleanupTestInstitute(db: DrizzleDB, tenant: TestInstitute): Promise<void> {
  await withAdmin(db, async (tx) => {
    await tx.delete(memberships).where(eq(memberships.tenantId, tenant.tenantId));
    await tx.delete(roles).where(eq(roles.tenantId, tenant.tenantId));
    await tx.delete(institutes).where(eq(institutes.id, tenant.tenantId));
    await tx.delete(users).where(eq(users.id, tenant.userId));
  });
}

/**
 * Delete everything `createTestReseller` created.
 */
export async function cleanupTestReseller(db: DrizzleDB, reseller: TestReseller): Promise<void> {
  await withAdmin(db, async (tx) => {
    await tx
      .delete(resellerMemberships)
      .where(eq(resellerMemberships.resellerId, reseller.resellerId));
    await tx
      .delete(roles)
      .where(and(eq(roles.resellerId, reseller.resellerId), eq(roles.scope, 'reseller')));
    await tx.delete(resellers).where(eq(resellers.id, reseller.resellerId));
    await tx.delete(users).where(eq(users.id, reseller.userId));
  });
}
