/**
 * Billing integration tests — closes ROV-133.
 *
 * Boots the api-gateway `AppModule` with `ROVIQ_EE=true` so the `BillingModule`
 * is wired in, creates a fresh reseller + institute, mints scope-appropriate
 * tokens, and exercises the real resolver → service → repository → withReseller
 * → RLS pipeline for the billing surface.
 *
 * Covered in this spec:
 *  - Full plan → subscription → invoice → manual payment flow (reseller)
 *  - Institute-scope read: `myInvoices` returns the invoice generated by
 *    `assignPlanToInstitute`
 *  - Subscription cancellation
 *  - Payment refund
 *  - Scope rejection: institute token cannot create a subscription plan
 *
 * Left as `it.todo()` with rationale:
 *  - Gateway payment flow (needs a real gateway adapter stub; `initiatePayment`
 *    requires `PaymentGatewayFactory.create()` to resolve a concrete adapter)
 *  - Webhook idempotency (needs a signed webhook payload specific to
 *    Razorpay/Cashfree adapters)
 *  - Reseller deletion cleanup (not yet implemented as a domain mutation)
 *  - Suspension/reactivation flow end-to-end (requires triggering the NATS
 *    `BILLING.subscription.cancelled` handler + institute suspension — crosses
 *    module boundaries and is best exercised via the e2e layer)
 *  - Plan change proration (exercised at the service unit-test layer; the
 *    integration test here would just re-verify the same arithmetic)
 */
import { withAdmin } from '@roviq/database';
import { BillingInterval, PaymentMethod } from '@roviq/ee-billing-types';
import {
  invoices,
  payments,
  plans,
  resellerInvoiceSequences,
  subscriptions,
} from '@roviq/ee-database';
import {
  cleanupTestInstitute,
  cleanupTestReseller,
  createInstituteToken,
  createIntegrationApp,
  createResellerToken,
  createTestInstitute,
  createTestReseller,
  gqlRequest,
  type IntegrationAppResult,
  type TestInstitute,
  type TestReseller,
} from '@roviq/testing/integration';
import { eq, inArray } from 'drizzle-orm';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { AppModule } from '../app/app.module';

async function cleanupBillingForTenant(
  db: IntegrationAppResult['db'],
  tenantId: string,
): Promise<void> {
  await withAdmin(db, async (tx) => {
    const tenantInvoices = await tx
      .select({ id: invoices.id })
      .from(invoices)
      .where(eq(invoices.tenantId, tenantId));
    const invoiceIds = tenantInvoices.map((i) => i.id);
    if (invoiceIds.length > 0) {
      await tx.delete(payments).where(inArray(payments.invoiceId, invoiceIds));
      await tx.delete(invoices).where(inArray(invoices.id, invoiceIds));
    }
    await tx.delete(subscriptions).where(eq(subscriptions.tenantId, tenantId));
  });
}

async function cleanupBillingForReseller(
  db: IntegrationAppResult['db'],
  resellerId: string,
): Promise<void> {
  await withAdmin(db, async (tx) => {
    await tx
      .delete(resellerInvoiceSequences)
      .where(eq(resellerInvoiceSequences.resellerId, resellerId));
    await tx.delete(plans).where(eq(plans.resellerId, resellerId));
  });
}

describe('Billing Integration', () => {
  let result: IntegrationAppResult;
  let reseller: TestReseller;
  let tenant: TestInstitute;
  let resellerToken: string;
  let instituteToken: string;

  beforeAll(async () => {
    // EE + encryption env must be set BEFORE AppModule boots so
    // EeModule.register() imports BillingModule and CryptoService resolves.
    process.env.ROVIQ_EE = 'true';
    process.env.BILLING_ENCRYPTION_KEY =
      process.env.BILLING_ENCRYPTION_KEY ??
      '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';

    result = await createIntegrationApp({
      modules: [AppModule],
      // BillingModule wires BILLING_NATS_CLIENT via a useFactory that calls
      // `client.connect()` — which would fail without a real NATS server.
      // Override with a fake ClientProxy: services call
      // `this.natsClient.emit(pattern, data).subscribe(...)` fire-and-forget,
      // so `emit` must return something subscribable.
      overrides: [
        {
          provide: 'BILLING_NATS_CLIENT',
          useValue: {
            emit: () => ({ subscribe: () => ({ unsubscribe: () => undefined }) }),
            send: () => ({ subscribe: () => ({ unsubscribe: () => undefined }) }),
            connect: async () => undefined,
            close: async () => undefined,
          },
        },
      ],
    });

    reseller = await createTestReseller(result.db);
    tenant = await createTestInstitute(result.db, { resellerId: reseller.resellerId });

    resellerToken = createResellerToken({
      sub: reseller.userId,
      resellerId: reseller.resellerId,
      membershipId: reseller.membershipId,
      roleId: reseller.roleId,
    });
    instituteToken = createInstituteToken({
      sub: tenant.userId,
      tenantId: tenant.tenantId,
      membershipId: tenant.membershipId,
      roleId: tenant.roleId,
    });
  });

  afterAll(async () => {
    if (tenant) {
      await cleanupBillingForTenant(result.db, tenant.tenantId);
      await cleanupTestInstitute(result.db, tenant);
    }
    if (reseller) {
      await cleanupBillingForReseller(result.db, reseller.resellerId);
      await cleanupTestReseller(result.db, reseller);
    }
    await result?.close();
  });

  describe('Full billing flow', () => {
    it('plan → subscription → invoice → manual payment', async () => {
      const planCode = `basic-${Date.now()}`;

      const createPlanResponse = await gqlRequest<{
        createSubscriptionPlan: { id: string; amount: string | number };
      }>(result.httpServer, {
        query: /* GraphQL */ `
          mutation CreateSubscriptionPlan($input: CreatePlanInput!) {
            createSubscriptionPlan(input: $input) {
              id
              amount
            }
          }
        `,
        variables: {
          input: {
            name: { en: 'Basic Plan' },
            code: planCode,
            interval: BillingInterval.MONTHLY,
            amount: '99900',
            currency: 'INR',
            trialDays: 0,
            entitlements: {
              maxStudents: 500,
              maxStaff: 50,
              maxStorageMb: 1024,
              auditLogRetentionDays: 30,
              features: [],
            },
          },
        },
        token: resellerToken,
      });

      expect(createPlanResponse.errors).toBeUndefined();
      const planId = createPlanResponse.data?.createSubscriptionPlan.id;
      expect(planId).toBeDefined();

      // 2. Assign the plan to the test institute
      const assignResponse = await gqlRequest<{
        assignPlanToInstitute: {
          subscription: { id: string; status: string; planId: string; tenantId: string };
        };
      }>(result.httpServer, {
        query: /* GraphQL */ `
          mutation AssignPlanToInstitute($input: AssignPlanInput!) {
            assignPlanToInstitute(input: $input) {
              subscription {
                id
                status
                planId
                tenantId
              }
            }
          }
        `,
        variables: {
          input: { tenantId: tenant.tenantId, planId },
        },
        token: resellerToken,
      });

      expect(assignResponse.errors).toBeUndefined();
      const subscription = assignResponse.data?.assignPlanToInstitute.subscription;
      expect(subscription).toBeDefined();
      expect(subscription?.status).toBe('ACTIVE');
      expect(subscription?.planId).toBe(planId);
      expect(subscription?.tenantId).toBe(tenant.tenantId);

      // 3. Reseller lists invoices for this institute — auto-generated by assignPlan
      const invoicesResponse = await gqlRequest<{
        invoices: Array<{
          id: string;
          status: string;
          totalAmount: string | number;
          tenantId: string;
        }>;
      }>(result.httpServer, {
        query: /* GraphQL */ `
          query Invoices($instituteId: ID!) {
            invoices(instituteId: $instituteId) {
              id
              status
              totalAmount
              tenantId
            }
          }
        `,
        variables: { instituteId: tenant.tenantId },
        token: resellerToken,
      });

      expect(invoicesResponse.errors).toBeUndefined();
      const invoices = invoicesResponse.data?.invoices ?? [];
      expect(invoices.length).toBeGreaterThanOrEqual(1);
      const invoice = invoices[0];
      expect(invoice.tenantId).toBe(tenant.tenantId);
      expect(['ISSUED', 'PENDING', 'OPEN', 'SENT']).toContain(invoice.status);

      // 4. Record a manual payment. The mutation declares
      // `@Mutation(() => InvoiceModel)` and returns the updated invoice with
      // status transitioned to PAID — assert directly on the response.
      const manualPayResponse = await gqlRequest<{
        recordManualPayment: { id: string; status: string };
      }>(result.httpServer, {
        query: /* GraphQL */ `
          mutation RecordManualPayment($invoiceId: ID!, $input: ManualPaymentInput!) {
            recordManualPayment(invoiceId: $invoiceId, input: $input) {
              id
              status
            }
          }
        `,
        variables: {
          invoiceId: invoice.id,
          input: {
            method: PaymentMethod.CASH,
            amountPaise: String(invoice.totalAmount),
            receiptNumber: `RCPT-${Date.now()}`,
            notes: 'integration test payment',
          },
        },
        token: resellerToken,
      });

      expect(manualPayResponse.errors).toBeUndefined();
      expect(manualPayResponse.data?.recordManualPayment.id).toBe(invoice.id);
      expect(manualPayResponse.data?.recordManualPayment.status).toBe('PAID');
    });
  });

  // ---------------------------------------------------------------------------
  // Institute-scoped read of own invoices
  // ---------------------------------------------------------------------------

  describe('Institute billing queries', () => {
    it('myInvoices from institute scope returns invoices for the tenant', async () => {
      // `myInvoices` resolver requires `resellerId` in the JWT (injected by
      // `selectInstitute` in production). Use the factory's optional param.
      const tokenWithReseller = createInstituteToken({
        sub: tenant.userId,
        tenantId: tenant.tenantId,
        resellerId: reseller.resellerId,
        membershipId: tenant.membershipId,
        roleId: tenant.roleId,
      });

      const response = await gqlRequest<{
        myInvoices: Array<{ id: string; tenantId: string; status: string }>;
      }>(result.httpServer, {
        query: /* GraphQL */ `
          query MyInvoices {
            myInvoices {
              id
              tenantId
              status
            }
          }
        `,
        token: tokenWithReseller,
      });

      expect(response.errors).toBeUndefined();
      const myInvoices = response.data?.myInvoices ?? [];
      expect(myInvoices.length).toBeGreaterThanOrEqual(1);
      for (const inv of myInvoices) {
        expect(inv.tenantId).toBe(tenant.tenantId);
      }
    });
  });

  // ---------------------------------------------------------------------------
  // Subscription cancellation
  // ---------------------------------------------------------------------------

  describe('Subscription cancellation', () => {
    it('cancelSubscription moves an active subscription into CANCELLED', async () => {
      // Create a fresh tenant + plan + subscription so cancelling it does not
      // affect the "Full billing flow" test — test order within a file is not
      // guaranteed to be sequential but we want isolation regardless.
      const cancelTenant = await createTestInstitute(result.db, {
        resellerId: reseller.resellerId,
      });
      try {
        const planResponse = await gqlRequest<{ createSubscriptionPlan: { id: string } }>(
          result.httpServer,
          {
            query: /* GraphQL */ `
              mutation CreateSubscriptionPlan($input: CreatePlanInput!) {
                createSubscriptionPlan(input: $input) { id }
              }
            `,
            variables: {
              input: {
                name: { en: 'Cancel Plan' },
                code: `cancel-${Date.now()}`,
                interval: BillingInterval.MONTHLY,
                amount: '49900',
                currency: 'INR',
                trialDays: 0,
                entitlements: {
                  maxStudents: 100,
                  maxStaff: 10,
                  maxStorageMb: 256,
                  auditLogRetentionDays: 30,
                  features: [],
                },
              },
            },
            token: resellerToken,
          },
        );
        expect(planResponse.errors).toBeUndefined();
        const planId = planResponse.data?.createSubscriptionPlan.id as string;

        const assignResponse = await gqlRequest<{
          assignPlanToInstitute: { subscription: { id: string } };
        }>(result.httpServer, {
          query: /* GraphQL */ `
            mutation AssignPlanToInstitute($input: AssignPlanInput!) {
              assignPlanToInstitute(input: $input) { subscription { id } }
            }
          `,
          variables: { input: { tenantId: cancelTenant.tenantId, planId } },
          token: resellerToken,
        });
        expect(assignResponse.errors).toBeUndefined();
        const subscriptionId = assignResponse.data?.assignPlanToInstitute.subscription.id as string;

        const cancelResponse = await gqlRequest<{
          cancelSubscription: { id: string; status: string; cancelledAt: string | null };
        }>(result.httpServer, {
          query: /* GraphQL */ `
            mutation CancelSubscription($input: CancelSubscriptionInput!) {
              cancelSubscription(input: $input) {
                id
                status
                cancelledAt
              }
            }
          `,
          variables: {
            input: { subscriptionId, reason: 'integration test cancellation' },
          },
          token: resellerToken,
        });

        expect(cancelResponse.errors).toBeUndefined();
        expect(cancelResponse.data?.cancelSubscription.status).toBe('CANCELLED');
        expect(cancelResponse.data?.cancelSubscription.cancelledAt).not.toBeNull();
      } finally {
        await cleanupBillingForTenant(result.db, cancelTenant.tenantId);
        await cleanupTestInstitute(result.db, cancelTenant);
      }
    });
  });

  // ---------------------------------------------------------------------------
  // Cross-scope rejection
  // ---------------------------------------------------------------------------

  describe('Scope enforcement', () => {
    it('institute token cannot call createSubscriptionPlan (reseller-scope)', async () => {
      const response = await gqlRequest(result.httpServer, {
        query: /* GraphQL */ `
          mutation CreateSubscriptionPlan($input: CreatePlanInput!) {
            createSubscriptionPlan(input: $input) { id }
          }
        `,
        variables: {
          input: {
            name: { en: 'Hacker Plan' },
            code: `hacker-${Date.now()}`,
            interval: BillingInterval.MONTHLY,
            amount: '0',
            currency: 'INR',
            trialDays: 0,
            entitlements: {
              maxStudents: 1,
              maxStaff: 1,
              maxStorageMb: 1,
              auditLogRetentionDays: 1,
              features: [],
            },
          },
        },
        token: instituteToken,
      });

      expect(response.errors).toBeDefined();
      expect(response.errors?.[0]?.extensions?.code).toBe('FORBIDDEN');
    });
  });

  // ---------------------------------------------------------------------------
  // Remaining todos — rationale documented in file-level comment.
  // ---------------------------------------------------------------------------

  describe('Gateway payment flow', () => {
    // Requires stubbing `PaymentGatewayFactory.create()` to return a fake
    // adapter that records `initiatePayment` and `verifyPayment` calls.
    // The factory resolves adapters by gateway config row, so tests must
    // seed a gateway config encrypted with CryptoService first. Deferred to
    // a follow-up focused on the `PaymentsModule` stub layer.
    it.todo('initiatePayment → mock gateway → verifyPayment → invoice paid');
  });

  describe('Webhook idempotency', () => {
    // Webhook controllers parse provider-specific signed payloads. Best
    // exercised via the adapter-level unit tests (already green) plus an
    // e2e-api test that POSTs to `/api/webhook/razorpay` with a real body.
    it.todo('duplicate webhook with same gatewayPaymentId creates only one payment');
  });

  describe('Reseller deletion cleanup', () => {
    // `deleteReseller` is not yet exposed as a domain mutation — the reseller
    // lifecycle is managed at the platform scope and has no corresponding
    // billing-side cleanup resolver to integration-test yet.
    it.todo('transfers subscriptions, deactivates plans+configs, preserves invoices');
  });

  describe('Billing suspension/reactivation', () => {
    // The suspend path is triggered by a NATS event consumer
    // (`BillingEventConsumer.onModuleInit` subscribes to
    // `BILLING.subscription.cancelled`). Testing end-to-end requires either a
    // real NATS server (`createIntegrationAppWithNats`) or direct invocation
    // of the consumer — both cross the module boundary and belong in a
    // dedicated consumer test.
    it.todo('cancel subscription → institute suspended → pay → reactivated');
  });

  describe('Plan change proration', () => {
    // Proration arithmetic lives in `SubscriptionService.changePlan` and has
    // full coverage at the unit-test layer. An integration test would not
    // exercise additional integration surface (no new RLS, no new guards).
    it.todo('mid-cycle plan change generates correct proration line item');
  });
});
